insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('1','Licencia con Categoria diferente',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('2','Contramano',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('3','Utilizar Celular',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('4','Circular sin Casco',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('5','Carga y Descarga',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('6','Maniobra Peligrosa',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('7','Sin VTV',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('8','Sin Seguro',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('9','Sin Chapa Patente',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('10','Transito Pesado',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('11','Acompañante Menor',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('12','Conductor Menor',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('13','Semaforo en Rojo',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('14','Sin Licencia de Conducir',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('15','Mal Estacionado',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('16','Sin Cinturon de Seguridad',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('17','No Acata Ordenes',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('18','Transito en Lugar Prohibido',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('19','Sin Cedula Verde',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('20','Art 44 Inc 2',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('21','Obtruccion descenso de pasajeros',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('22','Cedula Rosa Vencida',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('23','Giro Prohibido',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('24','Sin Espejo Retrovisor',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('25','Caducidad de datos Art 16',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('26','Licencia Vencida',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('27','Exceso de Dimenciones',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('28','Conduce sin anteojos recetados',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('29','Alcoholemia Positiva',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('31','Cedula Verde Vencida',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('32','Sin Habilitacion p/Remis',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('33','Sin Matafuego',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('34','Menor en asiento delantero',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('35','Acompañante sin Casco',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('36','Exceso de Carga',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('37','Mas de 1 Acompañante',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('38','Documentacion Presuntamente Apocrifa',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('39','Taxi Chofer No Declarado',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('40','Chapa Patente Mal Ubicada',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('41','Sin Luces Reglamentarias',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('42','Abandono de Vehiculo',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('43','Parabrisas no Reglamentario',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('44','Documentacion Deteriorada',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('45','Cedula Azul vencida',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('46','Sin Habilitacion p/Pasajeros',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('47','Se Niega a Exhibir Documentacion',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('48','Vehiculo no adaptado según licencia',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('49','Carga Descubierta',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('50','Utilizar Auricular',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('51','Exceso de Pasajeros',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('52','Sin Cedula Azul',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('53','Sin Cedula Rosa',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('54','Estacionamiento mas de 72 horas',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('55','Alcoholemia Presunta',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('56','No Posee Documentacion',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('57','Alteracion de Elementos',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('58','Cruzar Barreras Bajas',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('59','Sin Paragolpe',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('60','Se Da a la Fuga',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('61','No Recibe Copia de Acta',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('62','Descarga de Reciduos',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('64','Alcoholemia Negativa',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('65','Sin sistemas de seguridad',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('66','Falta de Categoria Habilitante',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('67','Se Niega a Test de Alcoholemia',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('68','Abandona Documentacion',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('69','Exceso de Velocidad',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('70','Sin Habilitacion Transporte Escolar',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('71','Agrecion Verbal',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('72','Circular Marcha Atrás',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('73','Cubiertas Lisas',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('74','Escape Alterado',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('75','Intento de Soborno',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('76','Obtruccion Senda Peatonal',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('77','Agresion Fisica',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('78','Provoca Colision',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('79','Trailler No Autorizado',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('81','Art 40 K',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('82','Vision Monocular',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('83','circula contramano',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('84','sin tablero reglamentario',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('85','Sin Descripcion',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('86','Sobre pasa vehículo',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('87','se detiene sobre peatonal',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('88','Sin habilitacion para sustancias alimenticias',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('89','Circula con polarizado',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('90','Licencia presuntamente apócrifa',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('91','arroja residuos en vía pública',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('92','Art 48 inc P',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('93','Art. 72 inc 8 D',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('94','Vidrio polarizado',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('95','Presunta VTV apócrifa',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('96','Circula sobre vereda',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('97','Excede capacidad transportativa',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('98','Circula por lugar no apto',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('99','Circula lugar prohibido',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('100','Circula con carga descubierta',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('101','detencion irregular sobre calzada',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('102','abandono de documentación',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('103','Circula con menor',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('104','Oblea VTV',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('105','Planilla VTV',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('106','sin habilitacion para transporte de pasajeros',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('107','sin habilitacion de carga',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('108','art 20 Ley 13.927',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('109','Art 70',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('110','Sin Descripcion',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('111','Levantar pasajeros sin habilitacion',getdate(),1);												
insert into [dbo].[Contraventions] (NroArticulo, Descripcion, FechaAlta, Enable ) values ('112','Art 16 No posee categoria p/delivery',getdate(),1);												
