insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Auto',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Camioneta',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Camion',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Cuatriciclo',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Moto',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Omnibus',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Utilitario',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Acoplado',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Minibus',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Tractor',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Ciclomotor',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Autoelevador',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Chasis/Cabina',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Triciclo',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Trailler',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Semi',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Furgon',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Furgoneta',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Maquina Vial',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Jeep',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Rural',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Combi',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('Caudales',getdate(),1);								
insert into [dbo].[VehicleTypes] (Descripcion, FechaAlta, Enable) values ('carro traccion a sangre',getdate(),1);								
