insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Retenido',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Licencia Retenida',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Cedula Verde Retenida',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Ticket Alcoholemia Nº',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Con Informe',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Llave de Moto',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('D.N.I',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('cedula azul retenida',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('recibo seguro',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('denuncia policial',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Oblea VTV',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Planilla VTV',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Licencia retenida x 2',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Retenido Trailer',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('foto del carro',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Remitido a Comisaria',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Poliza',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Ticket Alcoholemia x 2',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Licencia Senasa',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('Ticket control de cargas',getdate(),1);								
insert into [dbo].[Observations] (Descripcion,FechaAlta,Enable) values ('acta fiscalización de peso',getdate(),1);								
